apiVersion: apps/v1
kind: Deployment 
metadata:
  name: publicweb38
  labels:
    app: publicweb38
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publicweb38
  template:  
    metadata:
      labels: 
        app: publicweb38
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']      
      containers:
        - name: publicweb38
          image: stacksimplify/kube-publicweb38:1.0.0-MySQLDB
          imagePullPolicy: Always
          ports: 
            - containerPort: 8080           
          env:
            - name: DB_HOSTNAME
              value: "mysql"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "webappdb"            
            - name: DB_USERNAME
              value: "dbadmin@akswebappsdb"            
            - name: DB_PASSWORD
              value: "Redhat1449"            
