apiVersion: v1
kind: Service
metadata:
  name: privateweb38-service
  labels: 
    app: privateweb38
spec:
  type: LoadBalancer
  selector:
    app: privateweb38
  ports: 
    - port: 80
      targetPort: 8080

